language: php
php:
  - 5.3

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - wget https://github.com/cakephp/cakephp/tarball/1.3.15 -O cake.tar.gz
  - tar xf cake.tar.gz
  - mv cakephp-cakephp-* ./cakephp
  - chmod -R 777 ./cakephp/app/tmp
  - wget http://downloads.sourceforge.net/simpletest/simpletest_1.0.1.tar.gz -O simpletest.tar.gz
  - tar xf simpletest.tar.gz
  - mv simpletest/ ./cakephp/app/vendors/
  - echo "<?php
    App::build(array(
    'plugins' => array('/home/vagrant/builds/k1LoW/'),
    ));
    " > cakephp/app/config/bootstrap.php
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'driver' => 'mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => ''
    );
    public \$test = array(
      'driver' => 'mysql',
      'persistent' => false,
      'host' => '0.0.0.0',
      'login' => 'root',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
    );
    public function __construct() {
      \$db = (!empty(\$_SERVER['DB'])) ? \$_SERVER['DB'] : 'mysql';
      if (\$db === 'pgsql') {
      \$this->default = \$this->test = array(
      'driver' => 'postgresql',
      'persistent' => false,
      'host' => '127.0.0.1',
      'login' => 'postgres',
      'password' => '',
      'database' => 'cakephp_test',
      'prefix' => '',
      'encoding' => 'utf8'
      );
      }
    }
    }" > cakephp/app/config/database.php
  - cd ./cakephp

script:
  - php cake/console/cake.php testsuite glue all